server:
  port: 8081

spring:
  application:
    name: university.management

  datasource:
    url: jdbc:mysql://localhost:3306/uni_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
          order_updates: true
          batch_versioned_data: true
          generate_statistics: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60s
    cache:
      type: redis
      redis:
        time-to-live: 600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.university.management.controller
  use-fqn: true

jwt:
  secret: "HiIamAnAndThisIsAverySecretKeyForUniversityManagementSystem2025"
  expiration: 86400000 # 1 ng√†y (ms)

google:
  recaptcha:
    secret: "6LedfR4sAAAAAHqBp2DKyB-PYzr0uf7wq9ZLemEe"
    verify-url: "https://www.google.com/recaptcha/api/siteverify"
    threshold: 0.5

application:
  security:
    adminKey: "admin"